### ISSUE TITLE
Support hash based navigation

### ISSUE THREAD

**Issue by gampleman** [dtwrks/elm-book#2]
Thanks for this nice project.

We would like to use this for our internal styleguide and documentation, but the way we deploy our monorepo, we use urls like:

`http://somedomain.co/styleguide.html` 

(there are other apps at the same level)

our apps that need client side routing solve this by using the older pattern:

`http://somedomain/styleguide.html#/foo/bar`

I am wondering if this could be implemented (perhaps as an option; although it does make it easier to deploy on static hosts so you might consider making it the default and having the current behavior be opt-in).

If you'd be willing to add it, I am happy to implement it (I'd appreciate some pointers on where in the API it should be exposed, as its not entirely clear where this would fit in the various option categories).

**Comment by georgesboris** [comment]
This should be pretty simple!

The routing logic is pretty stupid at the moment – there is just one single function for it on `src/ElmBook/Internal/Application.elm:625`. But I need to take a look at how the internal links are being generated to make sure there won't be any bugs… Do you know how could I reproduce this setup locally? It would make it a lot easier to test.

I know it's not ideal but I guess the best place for it would be on `ThemeOptions`. I'm kinda shy to ask for help mainly because there are parts of this codebase which I'm really not proud of 😄 but I guess this is a lame concern so if you're willing to take a stab at it I'm more than happy to talk to you about / review the changes.

But if you're not available then this is definitely something I can work on before the next release (~2 weeks I believe).
